/**
 * Generic SAE codes only. Manufacturer-defined codes (second digit 1 or 2)
 * differ per brand and are deliberately absent — an unlisted code surfaces as
 * "no description" rather than a wrong one.
 */
export const DTC_CATALOG: Record<string, string> = {
  // Fuel and air metering
  P0100: 'Mass or volume air flow circuit malfunction',
  P0101: 'Mass or volume air flow circuit range/performance',
  P0102: 'Mass or volume air flow circuit low input',
  P0103: 'Mass or volume air flow circuit high input',
  P0104: 'Mass or volume air flow circuit intermittent',
  P0105: 'Manifold absolute pressure/barometric pressure circuit malfunction',
  P0106: 'Manifold absolute pressure/barometric pressure range/performance',
  P0107: 'Manifold absolute pressure/barometric pressure circuit low input',
  P0108: 'Manifold absolute pressure/barometric pressure circuit high input',
  P0109: 'Manifold absolute pressure/barometric pressure circuit intermittent',
  P0110: 'Intake air temperature circuit malfunction',
  P0111: 'Intake air temperature circuit range/performance',
  P0112: 'Intake air temperature circuit low input',
  P0113: 'Intake air temperature circuit high input',
  P0114: 'Intake air temperature circuit intermittent',
  P0115: 'Engine coolant temperature circuit malfunction',
  P0116: 'Engine coolant temperature circuit range/performance',
  P0117: 'Engine coolant temperature circuit low input',
  P0118: 'Engine coolant temperature circuit high input',
  P0119: 'Engine coolant temperature circuit intermittent',
  P0120: 'Throttle/pedal position sensor A circuit malfunction',
  P0121: 'Throttle/pedal position sensor A circuit range/performance',
  P0122: 'Throttle/pedal position sensor A circuit low input',
  P0123: 'Throttle/pedal position sensor A circuit high input',
  P0124: 'Throttle/pedal position sensor A circuit intermittent',
  P0125: 'Insufficient coolant temperature for closed loop fuel control',
  P0126: 'Insufficient coolant temperature for stable operation',
  P0128: 'Coolant thermostat below regulating temperature',
  P0130: 'O2 sensor circuit malfunction (bank 1 sensor 1)',
  P0131: 'O2 sensor circuit low voltage (bank 1 sensor 1)',
  P0132: 'O2 sensor circuit high voltage (bank 1 sensor 1)',
  P0133: 'O2 sensor circuit slow response (bank 1 sensor 1)',
  P0134: 'O2 sensor circuit no activity detected (bank 1 sensor 1)',
  P0135: 'O2 sensor heater circuit malfunction (bank 1 sensor 1)',
  P0136: 'O2 sensor circuit malfunction (bank 1 sensor 2)',
  P0137: 'O2 sensor circuit low voltage (bank 1 sensor 2)',
  P0138: 'O2 sensor circuit high voltage (bank 1 sensor 2)',
  P0139: 'O2 sensor circuit slow response (bank 1 sensor 2)',
  P0140: 'O2 sensor circuit no activity detected (bank 1 sensor 2)',
  P0141: 'O2 sensor heater circuit malfunction (bank 1 sensor 2)',
  P0150: 'O2 sensor circuit malfunction (bank 2 sensor 1)',
  P0151: 'O2 sensor circuit low voltage (bank 2 sensor 1)',
  P0152: 'O2 sensor circuit high voltage (bank 2 sensor 1)',
  P0153: 'O2 sensor circuit slow response (bank 2 sensor 1)',
  P0154: 'O2 sensor circuit no activity detected (bank 2 sensor 1)',
  P0155: 'O2 sensor heater circuit malfunction (bank 2 sensor 1)',
  P0156: 'O2 sensor circuit malfunction (bank 2 sensor 2)',
  P0157: 'O2 sensor circuit low voltage (bank 2 sensor 2)',
  P0158: 'O2 sensor circuit high voltage (bank 2 sensor 2)',
  P0159: 'O2 sensor circuit slow response (bank 2 sensor 2)',
  P0160: 'O2 sensor circuit no activity detected (bank 2 sensor 2)',
  P0161: 'O2 sensor heater circuit malfunction (bank 2 sensor 2)',
  P0170: 'Fuel trim malfunction (bank 1)',
  P0171: 'System too lean (bank 1)',
  P0172: 'System too rich (bank 1)',
  P0173: 'Fuel trim malfunction (bank 2)',
  P0174: 'System too lean (bank 2)',
  P0175: 'System too rich (bank 2)',
  P0180: 'Fuel temperature sensor A circuit malfunction',
  P0181: 'Fuel temperature sensor A circuit range/performance',
  P0182: 'Fuel temperature sensor A circuit low input',
  P0183: 'Fuel temperature sensor A circuit high input',
  P0190: 'Fuel rail pressure sensor circuit malfunction',
  P0191: 'Fuel rail pressure sensor circuit range/performance',
  P0192: 'Fuel rail pressure sensor circuit low input',
  P0193: 'Fuel rail pressure sensor circuit high input',

  // Injector circuits
  P0200: 'Injector circuit malfunction',
  P0201: 'Injector circuit malfunction, cylinder 1',
  P0202: 'Injector circuit malfunction, cylinder 2',
  P0203: 'Injector circuit malfunction, cylinder 3',
  P0204: 'Injector circuit malfunction, cylinder 4',
  P0205: 'Injector circuit malfunction, cylinder 5',
  P0206: 'Injector circuit malfunction, cylinder 6',
  P0207: 'Injector circuit malfunction, cylinder 7',
  P0208: 'Injector circuit malfunction, cylinder 8',
  P0217: 'Engine over temperature condition',
  P0219: 'Engine overspeed condition',
  P0220: 'Throttle/pedal position sensor B circuit malfunction',
  P0221: 'Throttle/pedal position sensor B circuit range/performance',
  P0222: 'Throttle/pedal position sensor B circuit low input',
  P0223: 'Throttle/pedal position sensor B circuit high input',
  P0230: 'Fuel pump primary circuit malfunction',
  P0231: 'Fuel pump secondary circuit low',
  P0232: 'Fuel pump secondary circuit high',
  P0234: 'Engine overboost condition',
  P0299: 'Turbocharger/supercharger underboost',

  // Ignition and misfire
  P0300: 'Random or multiple cylinder misfire detected',
  P0301: 'Cylinder 1 misfire detected',
  P0302: 'Cylinder 2 misfire detected',
  P0303: 'Cylinder 3 misfire detected',
  P0304: 'Cylinder 4 misfire detected',
  P0305: 'Cylinder 5 misfire detected',
  P0306: 'Cylinder 6 misfire detected',
  P0307: 'Cylinder 7 misfire detected',
  P0308: 'Cylinder 8 misfire detected',
  P0309: 'Cylinder 9 misfire detected',
  P0310: 'Cylinder 10 misfire detected',
  P0311: 'Cylinder 11 misfire detected',
  P0312: 'Cylinder 12 misfire detected',
  P0320: 'Ignition/distributor engine speed input circuit malfunction',
  P0325: 'Knock sensor 1 circuit malfunction (bank 1)',
  P0326: 'Knock sensor 1 circuit range/performance (bank 1)',
  P0327: 'Knock sensor 1 circuit low input (bank 1)',
  P0328: 'Knock sensor 1 circuit high input (bank 1)',
  P0330: 'Knock sensor 2 circuit malfunction (bank 2)',
  P0331: 'Knock sensor 2 circuit range/performance (bank 2)',
  P0332: 'Knock sensor 2 circuit low input (bank 2)',
  P0333: 'Knock sensor 2 circuit high input (bank 2)',
  P0335: 'Crankshaft position sensor A circuit malfunction',
  P0336: 'Crankshaft position sensor A circuit range/performance',
  P0337: 'Crankshaft position sensor A circuit low input',
  P0338: 'Crankshaft position sensor A circuit high input',
  P0340: 'Camshaft position sensor circuit malfunction',
  P0341: 'Camshaft position sensor circuit range/performance',
  P0342: 'Camshaft position sensor circuit low input',
  P0343: 'Camshaft position sensor circuit high input',
  P0350: 'Ignition coil primary/secondary circuit malfunction',
  P0351: 'Ignition coil A primary/secondary circuit malfunction',
  P0352: 'Ignition coil B primary/secondary circuit malfunction',
  P0353: 'Ignition coil C primary/secondary circuit malfunction',
  P0354: 'Ignition coil D primary/secondary circuit malfunction',
  P0355: 'Ignition coil E primary/secondary circuit malfunction',
  P0356: 'Ignition coil F primary/secondary circuit malfunction',
  P0357: 'Ignition coil G primary/secondary circuit malfunction',
  P0358: 'Ignition coil H primary/secondary circuit malfunction',

  // Emissions systems
  P0400: 'Exhaust gas recirculation flow malfunction',
  P0401: 'Exhaust gas recirculation flow insufficient detected',
  P0402: 'Exhaust gas recirculation flow excessive detected',
  P0403: 'Exhaust gas recirculation circuit malfunction',
  P0404: 'Exhaust gas recirculation circuit range/performance',
  P0405: 'Exhaust gas recirculation sensor A circuit low',
  P0406: 'Exhaust gas recirculation sensor A circuit high',
  P0410: 'Secondary air injection system malfunction',
  P0411: 'Secondary air injection system incorrect flow detected',
  P0412: 'Secondary air injection system switching valve A circuit malfunction',
  P0420: 'Catalyst system efficiency below threshold (bank 1)',
  P0421: 'Warm-up catalyst efficiency below threshold (bank 1)',
  P0422: 'Main catalyst efficiency below threshold (bank 1)',
  P0430: 'Catalyst system efficiency below threshold (bank 2)',
  P0431: 'Warm-up catalyst efficiency below threshold (bank 2)',
  P0432: 'Main catalyst efficiency below threshold (bank 2)',
  P0440: 'Evaporative emission control system malfunction',
  P0441: 'Evaporative emission control system incorrect purge flow',
  P0442: 'Evaporative emission control system leak detected (small leak)',
  P0443: 'Evaporative emission control system purge control valve circuit malfunction',
  P0444: 'Evaporative emission control system purge control valve circuit open',
  P0445: 'Evaporative emission control system purge control valve circuit shorted',
  P0446: 'Evaporative emission control system vent control circuit malfunction',
  P0447: 'Evaporative emission control system vent control circuit open',
  P0448: 'Evaporative emission control system vent control circuit shorted',
  P0449: 'Evaporative emission control system vent valve/solenoid circuit malfunction',
  P0450: 'Evaporative emission control system pressure sensor malfunction',
  P0451: 'Evaporative emission control system pressure sensor range/performance',
  P0452: 'Evaporative emission control system pressure sensor low input',
  P0453: 'Evaporative emission control system pressure sensor high input',
  P0455: 'Evaporative emission control system leak detected (gross leak)',
  P0456: 'Evaporative emission control system leak detected (very small leak)',
  P0457: 'Evaporative emission control system leak detected (fuel cap loose or off)',
  P0460: 'Fuel level sensor circuit malfunction',
  P0461: 'Fuel level sensor circuit range/performance',
  P0462: 'Fuel level sensor circuit low input',
  P0463: 'Fuel level sensor circuit high input',

  // Vehicle speed, idle and auxiliary inputs
  P0500: 'Vehicle speed sensor malfunction',
  P0501: 'Vehicle speed sensor range/performance',
  P0502: 'Vehicle speed sensor circuit low input',
  P0503: 'Vehicle speed sensor intermittent/erratic/high',
  P0505: 'Idle control system malfunction',
  P0506: 'Idle control system RPM lower than expected',
  P0507: 'Idle control system RPM higher than expected',
  P0510: 'Closed throttle position switch malfunction',
  P0520: 'Engine oil pressure sensor/switch circuit malfunction',
  P0521: 'Engine oil pressure sensor/switch range/performance',
  P0522: 'Engine oil pressure sensor/switch low voltage',
  P0523: 'Engine oil pressure sensor/switch high voltage',
  P0530: 'A/C refrigerant pressure sensor circuit malfunction',
  P0532: 'A/C refrigerant pressure sensor circuit low input',
  P0533: 'A/C refrigerant pressure sensor circuit high input',
  P0562: 'System voltage low',
  P0563: 'System voltage high',
  P0571: 'Cruise control/brake switch A circuit malfunction',

  // Control module
  P0600: 'Serial communication link malfunction',
  P0601: 'Internal control module memory check sum error',
  P0602: 'Control module programming error',
  P0603: 'Internal control module keep alive memory error',
  P0604: 'Internal control module random access memory error',
  P0605: 'Internal control module read only memory error',
  P0606: 'ECM/PCM processor fault',
  P0607: 'Control module performance',
  P0620: 'Generator control circuit malfunction',
  P0621: 'Generator lamp L terminal circuit malfunction',
  P0622: 'Generator field F terminal circuit malfunction',
  P0630: 'VIN not programmed or incompatible',
  P0645: 'A/C clutch relay control circuit malfunction',
  P0650: 'Malfunction indicator lamp control circuit malfunction',

  // Transmission (generic)
  P0700: 'Transmission control system malfunction',
  P0701: 'Transmission control system range/performance',
  P0702: 'Transmission control system electrical',
  P0703: 'Torque converter/brake switch B circuit malfunction',
  P0705: 'Transmission range sensor circuit malfunction',
  P0706: 'Transmission range sensor circuit range/performance',
  P0707: 'Transmission range sensor circuit low input',
  P0708: 'Transmission range sensor circuit high input',
  P0710: 'Transmission fluid temperature sensor circuit malfunction',
  P0711: 'Transmission fluid temperature sensor range/performance',
  P0712: 'Transmission fluid temperature sensor circuit low input',
  P0713: 'Transmission fluid temperature sensor circuit high input',
  P0715: 'Input/turbine speed sensor circuit malfunction',
  P0716: 'Input/turbine speed sensor circuit range/performance',
  P0717: 'Input/turbine speed sensor circuit no signal',
  P0720: 'Output speed sensor circuit malfunction',
  P0721: 'Output speed sensor circuit range/performance',
  P0722: 'Output speed sensor circuit no signal',
  P0725: 'Engine speed input circuit malfunction',
  P0730: 'Incorrect gear ratio',
  P0731: 'Gear 1 incorrect ratio',
  P0732: 'Gear 2 incorrect ratio',
  P0733: 'Gear 3 incorrect ratio',
  P0734: 'Gear 4 incorrect ratio',
  P0735: 'Gear 5 incorrect ratio',
  P0740: 'Torque converter clutch circuit malfunction',
  P0741: 'Torque converter clutch circuit performance or stuck off',
  P0742: 'Torque converter clutch circuit stuck on',
  P0743: 'Torque converter clutch circuit electrical',
  P0750: 'Shift solenoid A malfunction',
  P0751: 'Shift solenoid A performance or stuck off',
  P0752: 'Shift solenoid A stuck on',
  P0755: 'Shift solenoid B malfunction',
  P0760: 'Shift solenoid C malfunction',
  P0765: 'Shift solenoid D malfunction',
  P0770: 'Shift solenoid E malfunction',

  // Diesel-specific and later powertrain
  P2002: 'Diesel particulate filter efficiency below threshold (bank 1)',
  P2004: 'Intake manifold runner control stuck open (bank 1)',
  P2006: 'Intake manifold runner control stuck closed (bank 1)',
  P2015: 'Intake manifold runner position sensor circuit range/performance (bank 1)',
  P2096: 'Post catalyst fuel trim system too lean (bank 1)',
  P2097: 'Post catalyst fuel trim system too rich (bank 1)',
  P2101: 'Throttle actuator control motor circuit range/performance',
  P2181: 'Cooling system performance',
  P2187: 'System too lean at idle (bank 1)',
  P2188: 'System too rich at idle (bank 1)',
  P2195: 'O2 sensor signal stuck lean (bank 1 sensor 1)',
  P2196: 'O2 sensor signal stuck rich (bank 1 sensor 1)',
  P2270: 'O2 sensor signal stuck lean (bank 1 sensor 2)',
  P2271: 'O2 sensor signal stuck rich (bank 1 sensor 2)',
  P2279: 'Intake air system leak',
  P242F: 'Diesel particulate filter restriction, ash accumulation',
  P2463: 'Diesel particulate filter restriction, soot accumulation',

  // Network communication
  U0001: 'High speed CAN communication bus',
  U0100: 'Lost communication with ECM/PCM A',
  U0101: 'Lost communication with transmission control module',
  U0102: 'Lost communication with transfer case control module',
  U0103: 'Lost communication with gear shift module',
  U0104: 'Lost communication with cruise control module',
  U0107: 'Lost communication with throttle actuator control module',
  U0121: 'Lost communication with ABS control module',
  U0128: 'Lost communication with park brake control module',
  U0140: 'Lost communication with body control module',
  U0155: 'Lost communication with instrument panel cluster',
  U0164: 'Lost communication with HVAC control module',
  U0184: 'Lost communication with radio',
  U0401: 'Invalid data received from ECM/PCM A',
  U0402: 'Invalid data received from transmission control module',
  U0415: 'Invalid data received from ABS control module',

  // Chassis
  C0035: 'Left front wheel speed sensor circuit',
  C0040: 'Right front wheel speed sensor circuit',
  C0045: 'Left rear wheel speed sensor circuit',
  C0050: 'Right rear wheel speed sensor circuit',
  C0121: 'Valve relay circuit malfunction',
  C0161: 'ABS/TCS brake switch circuit',
  C0265: 'Electronic brake control module motor circuit',
};
